<?php
$data = array (
  0 => 
  array (
    'cat_id' => '12',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '6',
    'cat_name' => '黑茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  2 => 
  array (
    'cat_id' => '1',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '16',
    'cat_name' => '白茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '18',
    'cat_name' => '乌龙茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '20',
    'cat_name' => '花茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '26',
    'cat_name' => '祁红',
    'measure_unit' => '克',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '25',
    'cat_name' => '信阳毛尖',
    'measure_unit' => '克',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  8 => 
  array (
    'cat_id' => '22',
    'cat_name' => '碧螺春',
    'measure_unit' => '克',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  9 => 
  array (
    'cat_id' => '24',
    'cat_name' => '太平猴魁茶',
    'measure_unit' => '克',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  10 => 
  array (
    'cat_id' => '21',
    'cat_name' => '龙井茶',
    'measure_unit' => '克',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  11 => 
  array (
    'cat_id' => '23',
    'cat_name' => '六安瓜片',
    'measure_unit' => '克',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  12 => 
  array (
    'cat_id' => '17',
    'cat_name' => '安吉白茶',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  13 => 
  array (
    'cat_id' => '30',
    'cat_name' => '铁观音',
    'measure_unit' => '克',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  14 => 
  array (
    'cat_id' => '32',
    'cat_name' => '台湾乌龙茶',
    'measure_unit' => '克',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  15 => 
  array (
    'cat_id' => '34',
    'cat_name' => '玫瑰花',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  16 => 
  array (
    'cat_id' => '33',
    'cat_name' => '茉莉花',
    'measure_unit' => '克',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
);
?>